deployment:
  namespace: "dev"
image:
  repository: nginx
  tag: "latest"
container:
  ports:
    - name: http
      containerPort: 80
      protocol: TCP
# service:
#   enabled: true
#   type: ClusterIP
#   port: 8080
#   protocol: TCP

# virtualService:
#   enabled: true
#   # match: automatically uses /{deployment-name}/ prefix if not provided
#   http:
#     - route:
#         - destination:
#             host: ""
#             port:
#               number: 8080
